### ISSUE TITLE
foto de perfil retornando nula

### ISSUE THREAD

**Issue by kzin** [neneds/APCSDK2#1]
Olá, estou usando o framework para fazer as requisições pro metamodelo e estou encontrando problemas na hora de buscar a foto de perfil.

Estou fazendo a chamada assim:

`APCUserManager.sharedManager.getUserPicture(userCod: 1662) { (operationResponse) in
                print(operationResponse)
            }`

e está me retornando:

`OperationResponse = [data = nil, status = CompletedSuccesfully]`

Sendo que se eu fizer essa requisição pelo swagger ele retorna a foto direitinho

![screen shot 2016-10-25 at 2 11 13 pm](https://cloud.githubusercontent.com/assets/6423193/19696306/f354b176-9abc-11e6-9bdc-fddf5f94d255.png)
![screen shot 2016-10-25 at 2 11 20 pm](https://cloud.githubusercontent.com/assets/6423193/19696307/f35c00ac-9abc-11e6-8da8-47fddbd69880.png)

**Comment by neneds** [comment]
E aí, cara
Qual a branch do sdk que você usando?

**Comment by kzin** [comment]
a master

**Comment by LucianoPAlmeida** [comment]
@kzin 
Olá, foi lançada uma nova release(1.1.7) com o que deveria ser a correção para este problema. No entanto não pude testar pois estou sem Xcode 7 e iOS 9 para testar swift 2 e como era algo simples só alterei. Mas acredito que funcione. Se o problema continuar só avisar aqui que eu verifico novamente.
Att. Luciano :)
